### ISSUE TITLE
When opened with an unsupported chain it hangs

### ISSUE THREAD

**Issue by saltyfacu** [saltyfacu/ape-tax#126]
When I open ape.tax using Arbitrum (an unsupported chain id), the site hangs saying "Loadgin Ex2". The console shows: 

Uncaught (in promise) e: Unsupported chain id: 42161. Supported chain ids are: 1,56,137,250,1337.
    at https://ape.tax/_next/static/chunks/pages/_app-778eacfcaeaafa42e331.js:1:179453

**Expected behavior**
Show something saying: change network.

**Comment by Major-Eth** [comment]
Fixed with #138
