### ISSUE TITLE
Webpage not showing data on polygon

### ISSUE THREAD

**Issue by vea45** [saltyfacu/ape-tax#131]
e.g. https://ape.tax/purpletwister

The vaults there don't show any related data...

![imagen](https://user-images.githubusercontent.com/3083168/133212874-cc2a6145-1dbf-4487-b174-e730d9888e38.png)

**Comment by saltyfacu** [comment]
Thanks @vea45 ! I can repodroduce this.

**Comment by vea45** [comment]
the issue is still there...

**Comment by saltyfacu** [comment]
This is because we don't have access to archive data in Matic. We are trying to emulate using an RPC on our side but it may fail. Do you have an RPC that lets us access historical data?

**Comment by vea45** [comment]
aps I din't know that. So I need to add your RPC? Sorry I can't help with that... I noticed as well that it's not possible to interact with the vault on the webpage. Is this related to the same RPC issue?
![imagen](https://user-images.githubusercontent.com/3083168/134160994-a9f5d94f-25b6-4ae7-8f74-94cbf52880f5.png)
